name: api_tests
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=2.19.0-406.0.dev <3.0.0'

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  collection: ^1.17.0
  dio: ^4.0.6
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  tuple: ^2.0.1
